# Generated by Django 5.2 on 2025-05-24 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('offer_type', models.CharField(choices=[('car', 'Car'), ('property', 'Property')], max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Offer Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_membership', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarOffer',
            fields=[
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='car_details', serialize=False, to='accounts.offer')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometers (KM)')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='property_details', serialize=False, to='accounts.offer')),
                ('build_date', models.PositiveIntegerField(blank=True, null=True)),
                ('square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (m²)')),
                ('room_type', models.CharField(choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+2', '2+2'), ('3+1', '3+1'), ('3+2', '3+2'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+1', '5+1'), ('5+2', '5+2'), ('5+3', '5+3'), ('5+4', '5+4'), ('6+1', '6+1'), ('6+2', '6+2'), ('6+3', '6+3'), ('6+4', '6+4'), ('7+1', '7+1'), ('7+2', '7+2'), ('7+3', '7+3'), ('8+', '8+')], max_length=100)),
                ('document_type', models.CharField(choices=[('tahsis_kocan', 'Tahsis Koçan'), ('turk_kocan', 'Türk Koçan'), ('esdeger_kocan', 'Eşdeğer Koçan')], max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='offer_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_cover_image', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3)),
                ('description', models.TextField()),
                ('offer_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_offer_responses', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.offer')),
                ('offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officially_made_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Offer Response',
                'verbose_name_plural': 'Admin Offer Responses',
                'ordering': ['-offer_date', '-created_at'],
            },
        ),
    ]
