# Generated by Django 5.2 on 2025-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caroffer',
            old_name='model_name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='caroffer',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('lpg', 'LPG'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caroffer',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caroffer',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi-automatic', 'Semi-Automatic')], default='Automatic', max_length=15),
            preserve_default=False,
        ),
    ]
