# Generated by Django 5.2 on 2025-05-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_email_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
