# Generated by Django 5.2 on 2025-05-23 07:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('offer_type', models.CharField(choices=[('car', 'Car'), ('property', 'Property')], max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometers (KM)')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('build_date', models.DateField(blank=True, null=True)),
                ('square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (m²)')),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Offer Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='offerimage',
            name='offer',
        ),
        migrations.AddField(
            model_name='offerimage',
            name='offer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.offer'),
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('offer_description', models.TextField()),
                ('offer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offer_responses', to=settings.AUTH_USER_MODEL)),
                ('user_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_responses', to='accounts.offer')),
            ],
            options={
                'ordering': ['-offer_date'],
            },
        ),
        migrations.DeleteModel(
            name='CustomerOffer',
        ),
    ]
