# Generated by Django 5.2 on 2025-05-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_offer_remove_offerimage_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='offer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.offer'),
        ),
    ]
