# Generated by Django 5.2 on 2025-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_offerimage_offer_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AddField(
            model_name='offerresponse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offerresponse',
            name='offer_price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='offerresponse',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerresponse',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
