# Generated by Django 5.2 on 2025-05-24 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['city', 'area'],
                'unique_together': {('city', 'area')},
            },
        ),
        migrations.CreateModel(
            name='PropertyAdvertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('price_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3)),
                ('address', models.TextField()),
                ('advertise_status', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=10)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.CharField(choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+2', '2+2'), ('3+1', '3+1'), ('3+2', '3+2'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+1', '5+1'), ('5+2', '5+2'), ('5+3', '5+3'), ('5+4', '5+4'), ('6+1', '6+1'), ('6+2', '6+2'), ('6+3', '6+3'), ('6+4', '6+4'), ('7+1', '7+1'), ('7+2', '7+2'), ('7+3', '7+3'), ('8+', '8+')], max_length=100)),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('residence', 'Residence'), ('twin_villa', 'Twin Villa'), ('penthouse', 'Penthouse'), ('bungalow', 'Bungalow'), ('family_house', 'Family House'), ('complete_building', 'Complete Building'), ('timeshare', 'Timeshare'), ('abandoned_building', 'Abandoned Building'), ('half_construction', 'Half Construction')], max_length=50)),
                ('advertisement_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=50)),
                ('gross_area', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_area', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('building_age', models.IntegerField(blank=True, null=True)),
                ('floor_location', models.IntegerField(blank=True, null=True)),
                ('housing_shape', models.CharField(blank=True, max_length=20, null=True)),
                ('warming_type', models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('central_heating', 'Central Heating'), ('underfloor_heating', 'Underfloor Heating'), ('stove', 'Stove (Wood/Coal)'), ('electric_heater', 'Electric Heater'), ('geothermal', 'Geothermal Heating'), ('solar', 'Solar Heating'), ('air_conditioner', 'Air Conditioner'), ('no_heating', 'No Heating')], max_length=50, null=True)),
                ('dues', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('dues_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('rent_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3)),
                ('available_for_loan', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('swap', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyExplanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('property_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='properties.propertyadvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyExternalFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elevator', models.BooleanField(default=False)),
                ('gardened', models.BooleanField(default=False)),
                ('fitness', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('thermal_insulation', models.BooleanField(default=False)),
                ('doorman', models.BooleanField(default=False)),
                ('car_park', models.BooleanField(default=False)),
                ('playground', models.BooleanField(default=False)),
                ('water_tank', models.BooleanField(default=False)),
                ('tennis_court', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('football_field', models.BooleanField(default=False)),
                ('basketball_field', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('pvc', models.BooleanField(default=False)),
                ('market', models.BooleanField(default=False)),
                ('siding', models.BooleanField(default=False)),
                ('fire_escape', models.BooleanField(default=False)),
                ('property_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_features', to='properties.propertyadvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='property_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertyadvertisement')),
            ],
            options={
                'ordering': ['-is_cover', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInteriorFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adsl', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('built_in_kitchen', models.BooleanField(default=False)),
                ('barbecue', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('laundry_room', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('wallpaper', models.BooleanField(default=False)),
                ('dressing_room', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('tv_satellite', models.BooleanField(default=False)),
                ('laminate', models.BooleanField(default=False)),
                ('marble_floor', models.BooleanField(default=False)),
                ('panel_door', models.BooleanField(default=False)),
                ('blinds', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('satin_plaster', models.BooleanField(default=False)),
                ('satin_color', models.BooleanField(default=False)),
                ('ceramic_floor', models.BooleanField(default=False)),
                ('video_intercom', models.BooleanField(default=False)),
                ('parquet', models.BooleanField(default=False)),
                ('spotlight', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('cloakroom', models.BooleanField(default=False)),
                ('underfloor_heating', models.BooleanField(default=False)),
                ('double_glazing', models.BooleanField(default=False)),
                ('parent_bathroom', models.BooleanField(default=False)),
                ('property_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interior_features', to='properties.propertyadvertisement')),
            ],
        ),
    ]
