# Generated by Django 5.2 on 2025-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyadvertisement',
            name='customer',
        ),
    ]
