# Generated by Django 5.2 on 2025-05-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='floor_location',
            field=models.CharField(blank=True, choices=[('basement', 'Basement'), ('ground_floor', 'Ground Floor'), ('1', '1st Floor'), ('2', '2nd Floor'), ('3', '3rd Floor'), ('4+', '4th Floor or Higher')], max_length=50, null=True),
        ),
    ]
