# Generated by Django 5.2 on 2025-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyadvertisement',
            name='advertisement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('residence', 'Residence'), ('flat', 'Flat'), ('mansion', 'Mansion')], max_length=50),
        ),
    ]
