# Generated by Django 5.2 on 2025-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_propertyadvertisement_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyadvertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
