# Generated by Django 5.2 on 2025-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyadvertisement_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['province', 'area'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='district',
            new_name='area',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('province', 'area')},
        ),
        migrations.RemoveField(
            model_name='propertyadvertisement',
            name='advertise_no',
        ),
        migrations.RemoveField(
            model_name='propertyadvertisement',
            name='rental_income',
        ),
        migrations.RemoveField(
            model_name='propertyadvertisement',
            name='rental_income_type',
        ),
        migrations.AddField(
            model_name='propertyadvertisement',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyadvertisement',
            name='rental_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='dues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='dues_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='floor_location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='price_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3),
        ),
        migrations.RemoveField(
            model_name='location',
            name='neighborhood',
        ),
    ]
