# Generated by Django 5.2 on 2025-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_location_options_rename_district_location_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'area'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='province',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='propertyadvertisement',
            old_name='dues_type',
            new_name='dues_currency',
        ),
        migrations.RenameField(
            model_name='propertyadvertisement',
            old_name='price_type',
            new_name='price_currency',
        ),
        migrations.RenameField(
            model_name='propertyadvertisement',
            old_name='rental_type',
            new_name='rent_currency',
        ),
        migrations.RemoveField(
            model_name='propertyadvertisement',
            name='front',
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='dues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='gross_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='net_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='propertyadvertisement',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'area')},
        ),
    ]
