# Generated by Django 5.2 on 2025-05-15 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customer_email_alter_customer_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdvertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advertise_no', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='TRY', max_length=3)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('cabrio', 'Cabrio'), ('minivan', 'Minivan')], max_length=50)),
                ('advertisement_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=50)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('advertise_status', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=10)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('gear_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi-automatic', 'Semi-Automatic')], max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('model_year', models.IntegerField()),
                ('case_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('steering_type', models.CharField(choices=[('right_steering_wheel', 'Right Steering Wheel'), ('left_steering_wheel', 'Left Steering Wheel')], max_length=20)),
                ('engine_displacement', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_power', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_advertisements', to='accounts.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarExplanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('car_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='vehicles.caradvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='CarExternalFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headlamp_xenon', models.BooleanField(default=False)),
                ('headlight_adaptive', models.BooleanField(default=False)),
                ('headlight_sensor', models.BooleanField(default=False)),
                ('electric_mirrors', models.BooleanField(default=False)),
                ('folding_mirrors', models.BooleanField(default=False)),
                ('mirrors_heated', models.BooleanField(default=False)),
                ('parking_sensor_rear', models.BooleanField(default=False)),
                ('parking_sensor_front', models.BooleanField(default=False)),
                ('rain_sensor', models.BooleanField(default=False)),
                ('alloy_wheel', models.BooleanField(default=False)),
                ('rear_window_defroster', models.BooleanField(default=False)),
                ('smart_tailgate', models.BooleanField(default=False)),
                ('car_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_features', to='vehicles.caradvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='car_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.caradvertisement')),
            ],
            options={
                'ordering': ['-is_cover', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CarInternalFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_armchair', models.BooleanField(default=False)),
                ('leather_fabric_armchair', models.BooleanField(default=False)),
                ('electric_windshields', models.BooleanField(default=False)),
                ('front_armrest', models.BooleanField(default=False)),
                ('rear_armrest', models.BooleanField(default=False)),
                ('keyless_drive', models.BooleanField(default=False)),
                ('forward_gear', models.BooleanField(default=False)),
                ('hydraulic_steering', models.BooleanField(default=False)),
                ('functional_steering_wheel', models.BooleanField(default=False)),
                ('adjustable_steering_wheel', models.BooleanField(default=False)),
                ('leather_steering_wheel', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('adaptive_cruise_control', models.BooleanField(default=False)),
                ('reverse_view_camera', models.BooleanField(default=False)),
                ('road_computer', models.BooleanField(default=False)),
                ('start_stop', models.BooleanField(default=False)),
                ('air_conditioner_digital', models.BooleanField(default=False)),
                ('digital_monitor', models.BooleanField(default=False)),
                ('car_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_features', to='vehicles.caradvertisement')),
            ],
        ),
    ]
