# Generated by Django 5.2 on 2025-05-24 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdvertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('cabrio', 'Cabrio'), ('minivan', 'Minivan')], max_length=50)),
                ('advertisement_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=50)),
                ('address', models.TextField()),
                ('advertise_status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('gear_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi-automatic', 'Semi-Automatic')], max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('ford', 'Ford'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mercedes-benz', 'Mercedes-Benz'), ('nissan', 'Nissan'), ('peugeot', 'Peugeot'), ('renault', 'Renault'), ('skoda', 'Skoda'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo')], max_length=100, null=True)),
                ('series', models.CharField(blank=True, choices=[('1-series', '1 Series'), ('2-series', '2 Series'), ('2008', '2008'), ('208', '208'), ('3-series', '3 Series'), ('3008', '3008'), ('308', '308'), ('4-series', '4 Series'), ('5-series', '5 Series'), ('5008', '5008'), ('508', '508'), ('7-series', '7 Series'), ('a-class', 'A-Class'), ('a1', 'A1'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('a6', 'A6'), ('a7', 'A7'), ('a8', 'A8'), ('amg-gt', 'AMG GT'), ('arteon', 'Arteon'), ('c-class', 'C-Class'), ('c-hr', 'C-HR'), ('camry', 'Camry'), ('captur', 'Captur'), ('ceed', 'Ceed'), ('civic', 'Civic'), ('cla', 'CLA'), ('clio', 'Clio'), ('cls', 'CLS'), ('corolla', 'Corolla'), ('cr-v', 'CR-V'), ('e-class', 'E-Class'), ('e-tron', 'e-tron'), ('elantra', 'Elantra'), ('fabia', 'Fabia'), ('fiesta', 'Fiesta'), ('focus', 'Focus'), ('g-class', 'G-Class'), ('gla', 'GLA'), ('glb', 'GLB'), ('glc', 'GLC'), ('gle', 'GLE'), ('gls', 'GLS'), ('golf', 'Golf'), ('gt-r', 'GT-R'), ('hilux', 'Hilux'), ('hr-v', 'HR-V'), ('i10', 'i10'), ('i20', 'i20'), ('i30', 'i30'), ('id.3', 'ID.3'), ('id.4', 'ID.4'), ('jazz', 'Jazz'), ('juke', 'Juke'), ('kadjar', 'Kadjar'), ('kamiq', 'Kamiq'), ('karoq', 'Karoq'), ('kodiaq', 'Kodiaq'), ('kona', 'Kona'), ('kuga', 'Kuga'), ('land-cruiser', 'Land Cruiser'), ('m-series', 'M Series'), ('megane', 'Megane'), ('micra', 'Micra'), ('mondeo', 'Mondeo'), ('mustang', 'Mustang'), ('navara', 'Navara'), ('nsx', 'NSX'), ('octavia', 'Octavia'), ('passat', 'Passat'), ('picanto', 'Picanto'), ('polo', 'Polo'), ('prius', 'Prius'), ('puma', 'Puma'), ('q2', 'Q2'), ('q3', 'Q3'), ('q5', 'Q5'), ('q7', 'Q7'), ('q8', 'Q8'), ('qashqai', 'Qashqai'), ('r8', 'R8'), ('ranger', 'Ranger'), ('rav4', 'RAV4'), ('rio', 'Rio'), ('s-class', 'S-Class'), ('s60', 'S60'), ('s90', 'S90'), ('santa-fe', 'Santa Fe'), ('sorento', 'Sorento'), ('sportage', 'Sportage'), ('stonic', 'Stonic'), ('superb', 'Superb'), ('supra', 'Supra'), ('t-roc', 'T-Roc'), ('tiguan', 'Tiguan'), ('touareg', 'Touareg'), ('tt', 'TT'), ('tucson', 'Tucson'), ('v60', 'V60'), ('v90', 'V90'), ('x-trail', 'X-Trail'), ('x1', 'X1'), ('x2', 'X2'), ('x3', 'X3'), ('x4', 'X4'), ('x5', 'X5'), ('x6', 'X6'), ('x7', 'X7'), ('xc40', 'XC40'), ('xc60', 'XC60'), ('xc90', 'XC90'), ('yaris', 'Yaris'), ('z4', 'Z4')], max_length=100, null=True)),
                ('model_year', models.IntegerField()),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('lpg', 'LPG'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=50, null=True)),
                ('steering_type', models.CharField(choices=[('right_steering_wheel', 'Right-Hand Drive'), ('left_steering_wheel', 'Left-Hand Drive')], max_length=50)),
                ('engine_displacement', models.IntegerField(blank=True, null=True)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarExplanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('car_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='vehicles.caradvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='CarExternalFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headlamp_xenon', models.BooleanField(default=False)),
                ('headlight_adaptive', models.BooleanField(default=False)),
                ('headlight_sensor', models.BooleanField(default=False)),
                ('electric_mirrors', models.BooleanField(default=False)),
                ('folding_mirrors', models.BooleanField(default=False)),
                ('mirrors_heated', models.BooleanField(default=False)),
                ('parking_sensor_rear', models.BooleanField(default=False)),
                ('parking_sensor_front', models.BooleanField(default=False)),
                ('rain_sensor', models.BooleanField(default=False)),
                ('alloy_wheel', models.BooleanField(default=False)),
                ('rear_window_defroster', models.BooleanField(default=False)),
                ('smart_tailgate', models.BooleanField(default=False)),
                ('car_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_features', to='vehicles.caradvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='car_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.caradvertisement')),
            ],
            options={
                'ordering': ['-is_cover', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CarInternalFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_armchair', models.BooleanField(default=False)),
                ('leather_fabric_armchair', models.BooleanField(default=False)),
                ('electric_windshields', models.BooleanField(default=False)),
                ('front_armrest', models.BooleanField(default=False)),
                ('rear_armrest', models.BooleanField(default=False)),
                ('keyless_drive', models.BooleanField(default=False)),
                ('forward_gear', models.BooleanField(default=False)),
                ('hydraulic_steering', models.BooleanField(default=False)),
                ('functional_steering_wheel', models.BooleanField(default=False)),
                ('adjustable_steering_wheel', models.BooleanField(default=False)),
                ('leather_steering_wheel', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('adaptive_cruise_control', models.BooleanField(default=False)),
                ('reverse_view_camera', models.BooleanField(default=False)),
                ('road_computer', models.BooleanField(default=False)),
                ('start_stop', models.BooleanField(default=False)),
                ('air_conditioner_digital', models.BooleanField(default=False)),
                ('digital_monitor', models.BooleanField(default=False)),
                ('car_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_features', to='vehicles.caradvertisement')),
            ],
        ),
    ]
