# Generated by Django 5.2 on 2025-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
