# Generated by Django 5.2 on 2025-05-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caradvertisement',
            old_name='gear_type',
            new_name='transmission',
        ),
        migrations.AddField(
            model_name='caradvertisement',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caradvertisement',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
