# Generated by Django 5.2 on 2025-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_caradvertisement_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='advertisement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caradvertisement',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('cabrio', 'Cabrio'), ('minivan', 'Minivan')], default='suv', max_length=50),
            preserve_default=False,
        ),
    ]
