# Generated by Django 5.2 on 2025-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_caradvertisement_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradvertisement',
            name='customer',
        ),
    ]
