# Generated by Django 5.2 on 2025-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_caradvertisement_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
