# Generated by Django 5.2 on 2025-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_caradvertisement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvertisement',
            name='price_type',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('TRY', 'TRY')], default='GBP', max_length=3),
        ),
    ]
