# Generated by Django 5.2 on 2025-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_caradvertisement_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradvertisement',
            name='advertise_no',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='district',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='model',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='province',
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='engine_displacement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=50, null=True),
        ),
    ]
